# Numpy练习

In [1]:
import numpy as np

## 1. 创建矩阵

In [2]:
# 直接把python的组合数据类型变成numpy的ndarray类型
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
array = np.array(ls)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# 创建全零矩阵
zeros = np.zeros(shape=(3, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# 创建全1矩阵
ones = np.ones(shape=(1,3,5))
print(ones)
ones = np.squeeze(ones)
print(ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 2. 获得矩阵的形状

In [5]:
aranged = np.arange(90).reshape(3,3,10)
print(aranged)
print(aranged.shape)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]]

 [[30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]]]
(3, 3, 10)


In [6]:
print(aranged.flatten())
print(aranged.flatten().shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
(90,)


## 3. ndarray转换成列表类型

In [7]:
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
array = np.array(ls)
print(array.tolist())

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
print(array.flatten().tolist())

[1, 2, 3, 4, 5, 6, 7, 8, 9]


#### 在编程时注意你所操作的数据的类型，ndarray和list之间无法直接运算

## 4. numpy的ndarray和python的列表有什么区别？

In [9]:
# ndarray
array1 = np.array([[1,2,3],
                   [1,2,3],
                   [1,2,3]])

array2 = np.array([[3,2,1],
                   [3,2,1],
                   [3,2,1]])

array_sum = array1 + array2
print('array1 + array2 = \n', array_sum)

array_diff = array1 - array2
print('array1 - array2 = \n', array_diff)

array_diff_squared = array_diff ** 2
print('array_diff_squared ** 2 = \n', array_diff_squared)

array_diff_squared_sqrted = np.sqrt(array_diff_squared)
print('sqrt(array_diff_squared) = \n', array_diff_squared_sqrted)

array_diff_squared_sqrted_sumed = np.sum(array_diff_squared_sqrted)
print('sum(array_diff_squared_sqrted) = \n', array_diff_squared_sqrted_sumed)

array1 + array2 = 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
array1 - array2 = 
 [[-2  0  2]
 [-2  0  2]
 [-2  0  2]]
array_diff_squared ** 2 = 
 [[4 0 4]
 [4 0 4]
 [4 0 4]]
sqrt(array_diff_squared) = 
 [[2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]]
sum(array_diff_squared_sqrted) = 
 12.0


In [10]:
# list
ls1 = [[1,2,3],
       [1,2,3],
       [1,2,3]]

ls2 = [[3,2,1],
       [3,2,1],
       [3,2,1]]

print(ls1 + ls2)

print(ls1 ** 2)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [3, 2, 1], [3, 2, 1], [3, 2, 1]]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

以上内容可基本支撑该课程实验

更多教程详见网页：https://www.numpy.org.cn/user/quickstart.html